backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import routers
from rest_framework.schemas import get_schema_view

from tasex import views

router = routers.DefaultRouter()
router.register('experiments', views.ExperimentViewSet, 'experiment')
router.register('panels', views.PanelViewSet, 'panel')

urlpatterns = [
    path('', TemplateView.as_view(
        template_name='tasex/welcome.html'
    ), name='welcome'),
    path('admin/', admin.site.urls),
    path('temp_gui/', include('tasex.urls')),
    path('demo/', include('demo.urls')),
    path('api/', include(router.urls)),
    path('api/swagger-ui/', TemplateView.as_view(
        template_name='tasex/swagger-ui.html',
        extra_context={'schema_url':'openapi-schema'}
    ), name='swagger-ui'),
    path('api/openapi/', get_schema_view(
            title="Tasting Experiments",
            version="1.0.0"
    ), name='openapi-schema'),
]

backend/demo/urls.py
from django.urls import path

from .views import IndexView, ChangePanelStatusView, ResetPanelView, GeneratePanelAnswersView


app_name = 'demo'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('status/', ChangePanelStatusView.as_view(), name='change_panel_status'),
    path('reset/', ResetPanelView.as_view(), name='reset_panel'),
    path('randomize/', GeneratePanelAnswersView.as_view(), name='randomize_panel'),
]

backend/tasex/urls.py
from django.urls import path

from .views import PanelView, render_qr_code, SampleSetsView, SamplePreparationView, UpdatePanelStatusView

app_name = 'tasex'

urlpatterns = [
    path('<pk>/', PanelView.as_view(), name='panel'),
    path('<pk>/qr/', render_qr_code, name='panel-qr'),
    path('<pk>/sets/', SampleSetsView.as_view(), name='panel-sets'),
    path('<pk>/products/', SamplePreparationView.as_view(), name='panel-prepare'),
    path('<pk>/status/<status>', UpdatePanelStatusView.as_view(), name='panel-update-status'),
]

backend/demo/models.py
from django.db import models

from tasex.models import Panel


class DemoInstance(models.Model):
    session_key = models.CharField(max_length=50)
    panel = models.ForeignKey(Panel, on_delete=models.CASCADE, related_name='sessions')
    created_at = models.DateTimeField(auto_now_add=True)


class DemoParam(models.Model):
    key = models.CharField(max_length=50)
    value = models.CharField(max_length=50)

backend/demo/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, RedirectView, View


from .utils import (ensure_demo_data, get_indistinguishable_result_id,
                    get_significant_result_id, get_session_panel, reset_panel, create_panel_results)
from tasex.models import Panel, Sample, SampleSet


class IndexView(TemplateView):
    template_name = 'demo/index.html'

    def dispatch(self, request, *args, **kwargs):
        # create session for anonymous user
        if not request.session or not request.session.session_key:
            request.session.save()
        # check and create demo data for session
        ensure_demo_data(request.session.session_key)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['result_significant_id'] = get_significant_result_id()
        context['result_indistinguishable_id'] = get_indistinguishable_result_id()
        context['panel'] = get_session_panel(self.request.session.session_key)
        sample_sets = SampleSet.objects.filter(panel=context['panel']).filter(is_used=False)
        context['sample_set'] = Sample.objects.filter(
            sample_set=sample_sets.first()
        ).values_list('code', flat=True)
        context['is_panel_full'] = sample_sets.count() == 0
        context['current_tab'] = self.request.session.get('current_tab')
        return context


class SetOwnPanelTabView(View):
    def dispatch(self, request, *args, **kwargs):
        request.session['current_tab'] = 'own_panel'
        request.session.save()
        return super().dispatch(request, *args, **kwargs)


class ChangePanelStatusView(RedirectView, SetOwnPanelTabView):
    url = reverse_lazy('demo:index')

    def post(self, request, *args, **kwargs):
        next_status = request.POST.get('set_status')
        if next_status in Panel.PanelStatus:
            panel = get_session_panel(request.session.session_key)
            panel.status = next_status
            panel.save()
        return super().post(request, *args, **kwargs)


class ResetPanelView(RedirectView, SetOwnPanelTabView):
    url = reverse_lazy('demo:index')

    def get(self, request, *args, **kwargs):
        reset_panel(get_session_panel(request.session.session_key))
        return super().get(request, *args, **kwargs)


class GeneratePanelAnswersView(RedirectView, SetOwnPanelTabView):
    url = reverse_lazy('demo:index')

    def post(self, request, *args, **kwargs):
        mode = request.POST.get('mode')
        panel = get_session_panel(request.session.session_key)
        if mode == 'different':
            probability = 0.66
        else:
            probability = 0.33
        create_panel_results(panel, probability, (0.6, 0.1, 0.3))
        return super().post(request, *args, **kwargs)

backend/demo/templates/demo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Triangle Testing Demo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}

</head>
<body class="bg-light-subtle">

    {% include 'demo/messages.html' %}
    {% include 'demo/header.html' %}
{#    {%  include 'demo/navbar.html' %}#}


    <div  class="container bg-light h-100 p-3 shadow">

        {% block content %}

        {% endblock %}
    </div>

</body>
</html>

backend/demo/templates/demo/header.html
<div class="container p-5 text-bg-primary text-center rounded-top shadow">
    <h1>Triangle Tests app demo presentation</h1>
</div>

backend/demo/templates/demo/index.html
{% extends 'demo/base.html' %}
{% load static %}
{% block content %}

    <div class="modal fade" id="QR" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <img id="qrImg"
                     class="img-responsive"
                     src=""
                     alt="scan to get the link"
                     width="100%"
                />
            </div>
        </div>
      </div>
    </div>

    <div id="fakeModal" class="modal hide" data-backdrop="static" data-keyboard="false"></div>

    <script>
    $(document).on("click", ".openQrModal", function () {
    var qrSrc = $(this).data('id');
    $(".modal-body #qrImg").attr("src", qrSrc);
    });
    </script>


    <p>
       If you do not know what triangle tests are, check out <a target="_blank" href="https://www.sensorysociety.org/knowledge/sspwiki/Pages/Triangle%20Test.aspx">this site</a>
    </p>
    <div class="accordion" id="appDescription">
      <div class="accordion-item">
        <h2 class="accordion-header" id="flow">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
              <span class="lead">The flow</span>
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="flow" data-bs-parent="#appDescription">
          <div class="accordion-body">
              <img src="{% static '/demo/flow.png' %}" alt="Action diagram"/>
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="features">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              <span class="lead">Features overview</span>
          </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="features" data-bs-parent="#appDescription">
          <div class="accordion-body">
              <p><strong>Define experiment. </strong> You may want to run more than one panel for the experiment -
                you can create default set of questions that will be asked after odd sample identification.
                Only answers from Panelists, who correctly identified the odd sample are used in stats calculation.
              </p>
              <p>
                  <strong>Create panel.</strong> You can change the questions copied from experiment definition if you want.
              </p>
              <p><strong>Prepare the samples.</strong> App provides you with easy to use list of random sample ids.
                  You will prepare equal number of samples of both products, as some Panelists will be served AAB sample set,
                  while others will get ABB sample set.
                  Sample preparation lists groups sample ids by product for easy preparation.
              </p>
              <p>
                  <strong>Serve the samples.</strong> App provides you with sample set lists so it's easy to assemble
                  previously prepared samples into sets ensuring random distribution. The Panelist's questionnaire's
                  first step verifies the sample set is correct.
              </p>
              <p>
                  <strong>Share the link to panel's questionnaire. </strong> There's no easier way than to show the QR
                  code to scan the link.
              </p>
              <p>
                 <strong>Gather the answers.</strong> Let the Panelists select the odd sample, followed by custom questions
                  defined for the panel (eg. 'Which product do you like more?').
              </p>
              <p>
                  <strong>Get the results</strong> The app calculates the p-value for the 'Samples are indistinguishable'
                  hypothesis. It also calculates the statistics for custom questions, dismissing answers provided by Panelists,
                  who failed to identify the odd sample.
              </p>
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="sampleResults">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            <span class="lead">See the results of example panels</span>
          </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="sampleResults" data-bs-parent="#appDescription">
          <div class="accordion-body">
            <table class="table table-hover">
                <tr>
                    <td>Significant amount of odd sample identification</td>
                    <td>
                        <a class="btn btn-outline-primary"
                           href="{% url 'tasex:panel' result_significant_id %}"
                           target="_blank">Open in new tab</a>
                    </td>
                    <td>
                        <a class="btn btn-outline-primary openQrModal"
                           data-id="{% url 'tasex:panel-qr' result_significant_id %}"
                           data-bs-toggle="modal"
                           data-bs-target="#QR">QR link</a>
                    </td>
                </tr>
                <tr>
                    <td>Too few odd sample identification to conclude samples differ</td>
                    <td>
                        <a class="btn btn-outline-primary"
                           href="{% url 'tasex:panel' result_indistinguishable_id %}"
                           target="_blank">Open in new tab</a>
                    </td>
                    <td>
                        <a class="btn btn-outline-primary openQrModal"
                           data-id="{% url 'tasex:panel-qr' result_indistinguishable_id %}"
                           data-bs-toggle="modal"
                           data-bs-target="#QR">QR link</a>
                    </td>
                </tr>
            </table>
          </div>
        </div>
      </div>
       <div class="accordion-item">
        <h2 class="accordion-header" id="playground">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
            <span class="lead">Play with your own panel</span>
          </button>
        </h2>
        <div id="collapseFour"
             class="accordion-collapse collapse {% if current_tab == 'own_panel' %}
                show
                {% endif %}"
             aria-labelledby="playground"
             data-bs-parent="#appDescription"
        >
          <div class="accordion-body">
          <p>We have created a panel for you:<ul>
              <li>10 panelists</li>
              <li>3 extra questions</li>
          </ul></p>
              <p>Set panel status to <strong>ACCEPT ANSWERS</strong> and open the panel as panelist in separate tab or scan the QR code and open on your mobile.
                  Fill in the form using samples' codes provided below (refresh after you've used them to get a new set).
              Generate random answers (in two modes) to finish the panel. Set status to <strong>SHOW RESULTS</strong>  to view the results of your panel</p>
          {% if sample_set %}
              <p>Here is the list of sample codes you can use to fill the panel form:</p>
              <ol>
              {% for sample in sample_set %}
                  <li>{{ sample }}</li>
              {% endfor %}
              </ol>
          {% endif %}

            <table class="table table-hover">
                <tr>
                    <td>Change status of the panel</td>
                    <td>
                        <form action="{% url 'demo:change_panel_status' %}" method="post">
                        {% csrf_token %}
                            <input type="hidden" name="set_status">
                            <button class="btn
                                {% if panel.status == 'PLANNED' %}
                                    btn-primary
                                {% else %}
                                    btn-outline-primary
                                {% endif %}"
                                onclick="
                                set_status.value='PLANNED'; form.submit();
                            ">Planned</button>
                             <button class="btn
                                {% if panel.status == 'ACCEPTING_ANSWERS' %}
                                    btn-primary
                                {% else %}
                                    btn-outline-primary
                                {% endif %}"
                                onclick="
                                set_status.value='ACCEPTING_ANSWERS'; form.submit();
                            ">Accepts answers</button>
                             <button class="btn
                                {% if panel.status == 'PRESENTING_RESULTS' %}
                                    btn-primary
                                {% else %}
                                    btn-outline-primary
                                {% endif %}"
                                onclick="
                                set_status.value='PRESENTING_RESULTS'; form.submit();
                            ">Show results</button>
                             <button class="btn
                                {% if panel.status == 'HIDDEN' %}
                                    btn-primary
                                {% else %}
                                    btn-outline-primary
                                {% endif %}"
                                onclick="
                                set_status.value='HIDDEN'; form.submit();
                            ">Hidden</button>
                        </form>
                    </td>
                </tr>
                <tr>
                    <td>Check the Panelist perspective (depends on status of the panel)</td>
                    <td>
                        <a class="btn btn-outline-primary"
                           href="{% url 'tasex:panel' panel.id %}"
                           target="_blank"
                        >
                            Open in new tab
                        </a>
                        <a class="btn btn-outline-primary openQrModal"
                           data-id="{% url 'tasex:panel-qr' panel.id %}"
                           data-bs-toggle="modal"
                           data-bs-target="#QR">QR link</a>
                    </td>
                </tr>
                <tr>
                    <td>Generate random answers for remaining Panelists in a way suggesting that samples are</td>
                    <td>
                        <form action="{% url 'demo:randomize_panel' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="mode">
                            <button
                                class="btn btn-outline-primary {% if is_panel_full %}disabled{% endif %}"
                                onclick="mode.value='different'; form.submit();"
                                data-bs-toggle="modal"
                                data-bs-target="#fakeModal"
                            >
                            Significantly different
                            </button>

                            <button
                                class="btn btn-outline-primary {% if is_panel_full %}disabled{% endif %}"
                                onclick="mode.value='indistinguishable'; form.submit();"
                                data-bs-toggle="modal"
                                data-bs-target="#fakeModal"
                            >
                            Indistinguishable
                            </button>
                        </form>
                    </td>
                </tr>
                <tr>
                    <td>Reset the panel and start from scratch</td>
                    <td>
                        <a
                            class="btn btn-outline-danger"
                            href="{% url 'demo:reset_panel' %}"
                        >Reset</a>

                    </td>
                </tr>
            </table>

          </div>
        </div>
      </div>

    </div>
{#    Modals#}



{% endblock content %}

backend/demo/templates/demo/messages.html
{% load bootstrap_icons %}
<div class="container px-0">
<div class="container my-5" style="position: fixed; z-index: 1061">

 {% for message in messages %}
              <div class="alert {{ message.tags }} alert-dismissible fade show rounded" role="alert" >
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                  <span aria-hidden="True">&times;</span>
                </button>
              {% if message.tags == 'alert-warning' or message.tags == 'alert-danger' %}
                  {% bs_icon 'exclamation-triangle-fill' size='1.5em' %}
              {% elif message.tags == 'alert-success' %}
                  {% bs_icon 'check-circle-fill' size='1.5em' %}
              {% elif message.tags == 'alert-info' %}
                  {% bs_icon 'info-circle-fill' size='1.5em' %}
              {% endif %}
              {{ message }}
              </div>
        {% endfor %}
        <script type="text/javascript">
            let alert_list = document.querySelectorAll('.alert')
            alert_list.forEach(function(alert) {
                new bootstrap.Alert(alert);

                let alert_timeout = alert.getAttribute('data-timeout');
                setTimeout(() => {
                    bootstrap.Alert.getInstance(alert).close();
                }, 5000);
            });
        </script>
</div></div>

backend/demo/templates/demo/navbar.html
{% load bootstrap_icons %}
{% load static %}
{% load i18n %}

<nav class="container navbar navbar-expand-sm text-bg-secondary navbar shadow py-1 px-3 sticky-top rounded-bottom">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item dropdown me-0">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownProfile" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {% bs_icon 'person-lines-fill' size='1.5em' %}
                    </a>

                    <ul class="dropdown-menu shadow" aria-labelledby="navbarDropdownProfile">
                        {% if user.is_authenticated %}
                            <li>
                                <h4 class="dropdown-header">
                                    {% translate "Logged in as:" %}<br/><small>{{ user.email }}</small>
                                </h4>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'contest:profile' %}">
                                    {# Translators: My profile button #}
                                    {% translate "My profile" %}
                                </a>
                            </li>

                            {%  if user.is_staff %}
                            <li>
                                <a class="dropdown-item" href="{% url 'admin:index' %}">
                                    {# Translators: Link to the Django admin panel #}
                                    {% translate "Django admin" %}
                                </a>
                            </li>
                            {% endif %}

                            <li><hr class="dropdown-divider"></hr></li>
                            <li>
                                <a class="dropdown-item" href="{% url 'account_logout' %}">
                                    {# Translators: Logout button #}
                                    {% translate "Logout" %}
                                </a>
                            </li>
                        {% else %}
                            <li>
                                <a class="dropdown-item" href="{% url 'account_login' %}">
                                    {# Translators: Login button #}
                                    {% translate "Login" %}
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'account_signup' %}">
                                    {# Translators: Register button #}
                                    {% translate "Register" %}
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </li>

                <li class="nav-item dropdown me-0">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {% bs_icon 'translate' size='1.5em' %}
                    </a>

                    <ul class="dropdown-menu shadow" aria-labelledby="navbarDropdownMenuLink">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}

                        <form action="{% url 'set_language' %}" method="post" id="lang-form">
                        <input name="next" type="hidden" value="{{ request.path }}" />
                        <input name="language" type="hidden">
                        {% csrf_token %}
                        {% for language  in languages %}
                            <li>
                                <button type="submit" class="dropdown-item text-capitalize"
                                onclick="this.form.language.value='{{ language.code }}'">
                                    {% if language.code == LANGUAGE_CODE %}
                                        <strong>{{ language.name_local }}</strong>
                                    {% else %}
                                        {{ language.name_local }}
                                    {% endif %}
                                </button>
                       {% endfor %}
                        </form>
                  </ul>
                </li>
{#Regular links start here#}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">
                        {# Translators: Link to homepage #}
                        {% translate "Home" %}
                    </a>
                </li>




            </ul>
        </div>
    </div>
</nav>