backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import routers
from rest_framework.schemas import get_schema_view

from tasex import views

router = routers.DefaultRouter()
router.register('experiments', views.ExperimentViewSet, 'experiment')
router.register('panels', views.PanelViewSet, 'panel')

urlpatterns = [
    path('', TemplateView.as_view(
        template_name='tasex/welcome.html'
    ), name='welcome'),
    path('admin/', admin.site.urls),
    path('temp_gui/', include('tasex.urls')),
    path('demo/', include('demo.urls')),
    path('api/', include(router.urls)),
    path('api/swagger-ui/', TemplateView.as_view(
        template_name='tasex/swagger-ui.html',
        extra_context={'schema_url':'openapi-schema'}
    ), name='swagger-ui'),
    path('api/openapi/', get_schema_view(
            title="Tasting Experiments",
            version="1.0.0"
    ), name='openapi-schema'),
]

backend/demo/urls.py
from django.urls import path

from .views import IndexView, ChangePanelStatusView, ResetPanelView, GeneratePanelAnswersView


app_name = 'demo'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('status/', ChangePanelStatusView.as_view(), name='change_panel_status'),
    path('reset/', ResetPanelView.as_view(), name='reset_panel'),
    path('randomize/', GeneratePanelAnswersView.as_view(), name='randomize_panel'),
]

backend/tasex/urls.py
from django.urls import path

from .views import PanelView, render_qr_code, SampleSetsView, SamplePreparationView, UpdatePanelStatusView

app_name = 'tasex'

urlpatterns = [
    path('<pk>/', PanelView.as_view(), name='panel'),
    path('<pk>/qr/', render_qr_code, name='panel-qr'),
    path('<pk>/sets/', SampleSetsView.as_view(), name='panel-sets'),
    path('<pk>/products/', SamplePreparationView.as_view(), name='panel-prepare'),
    path('<pk>/status/<status>', UpdatePanelStatusView.as_view(), name='panel-update-status'),
]

backend/tasex/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe

from .models import Product, Experiment, Panel, Sample, PanelQuestion
from .widgets import VerticalButtonSelect

class InternalNameChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        if hasattr(obj, 'internal_name'):
            if hasattr(obj, 'brew_id'):
                return f'{obj.internal_name} ({obj.brew_id})'
            return obj.internal_name
        if hasattr(obj, 'internal_title'):
            return obj.internal_title
        return obj.__str__


class ExperimentForm(forms.ModelForm):
    product_A = InternalNameChoiceField(queryset=Product.objects)
    product_B = InternalNameChoiceField(queryset=Product.objects)

    class Meta:
        model = Experiment
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        question_set_widget = self.fields['question_set'].widget
        question_set_widget.can_change_related = False
        question_set_widget.can_delete_related = False


class PanelFormAdd(forms.ModelForm):
    experiment = InternalNameChoiceField(queryset=Experiment.objects)
    create_questions = forms.ChoiceField(
        choices=(
            ('copy', "Copy questions from experiment's default question set"),
            ('blank', 'Let me create questions on my own')
        ),
        initial='copy'
    )

    class Meta:
        model = Panel
        fields = '__all__'


class PanelFormChange(forms.ModelForm):
    class Meta:
        model = Panel
        exclude = ('experiment', 'planned_panelists')


class PanelQuestionsForm(forms.Form):
    def __init__(self, *args, **kwargs):
        questions = kwargs.pop('questions', PanelQuestion.objects.none())
        super().__init__(*args, **kwargs)
        for question in questions:
            self.fields[question.id] = forms.ChoiceField(
                required=True,
                choices=question.scale.points.values_list('code', 'text'),
                # widget=forms.RadioSelect,
                widget=VerticalButtonSelect,
                label=question.question_text
            )

    def clean(self):
        for question in self.fields:
            answer = self.data.get(str(question))
            if answer and answer in PanelQuestion.objects.get(id=question).scale.points.values_list('code', flat=True):
                self.errors.pop(question)
        return self.data


class GenericPanelForm(forms.Form):
    def __init__(self, **kwargs):
        self.panel_state = kwargs.pop('panel_state')
        super().__init__(**kwargs)


class SingleSampleForm(GenericPanelForm):
    code = forms.IntegerField(
        label='Podaj numer dowolnej z otrzymanych próbek, abyśmy mogli sprawdzić czy masz dobry zestaw'
    )

    def clean_code(self):
        data = self.cleaned_data["code"]
        sample = Sample.objects.filter(code=data).filter(sample_set__panel_id=self.panel_state.panel_id)

        if not sample.exists():
            raise ValidationError('Nie ma takiego numeru próbki')

        if not sample.filter(sample_set__is_used=False).exists():
            raise ValidationError('Ten numer próbki został już wykorzystany')

        self.cleaned_data["sample_set_id"] = sample.values_list('sample_set_id')[0][0]

        return data


class CheckSampleSetForm(GenericPanelForm):
    are_samples_correct = forms.ChoiceField(
        # widget=forms.RadioSelect,
        widget=VerticalButtonSelect,
        choices=(
            (False, 'Nie'),
            (True, 'Tak'),
        )
    )

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        samples = Sample.objects.filter(sample_set_id=self.panel_state.sample_set).values_list('code', flat=True)
        self.fields['are_samples_correct'].label = mark_safe(
            f'Sprawdź, czy Twoje próbki mają poniższe numery: <h4>{", ".join(samples)}</h4>' +
            'Czy <b>wszystkie</b> numery się zgadzają?<br/>'
        )


class SelectOddSampleForm(GenericPanelForm):
    odd_sample = forms.ChoiceField(
        # widget=forms.RadioSelect,
        widget=VerticalButtonSelect,
        label=mark_safe('Która z próbek jest  <b>inna</b> od pozostałych?'
                        '<br/>Wybierz dowolną, jeśli Twoim zdaniem są takie same')
    )

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        samples = Sample.objects.filter(sample_set_id=self.panel_state.sample_set).values_list('id', 'code')
        self.fields['odd_sample'].choices = samples


FORM_CLASSES = {
    1: SingleSampleForm,
    2: CheckSampleSetForm,
    3: SelectOddSampleForm
}

backend/tasex/views.py
import qrcode

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import BadRequest, PermissionDenied, ValidationError
from django.db import models
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import reverse, get_object_or_404
from django.views.generic import DetailView, FormView, ListView, RedirectView
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets, permissions

from .forms import FORM_CLASSES, PanelQuestionsForm
from .models import Experiment, Panel, Sample, SampleSet, Product, Result, PanelQuestion, Answer

from .serializers import ExperimentSerializer, PanelSerializer
from .utils import PanelResult, SurveyPlots


class ExperimentViewSet(viewsets.ModelViewSet):
    serializer_class = ExperimentSerializer
    queryset = Experiment.objects.all()
    permission_classes = [permissions.IsAuthenticated]


class PanelViewSet(viewsets.ModelViewSet):
    serializer_class = PanelSerializer
    queryset = Panel.objects.all()
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ('experiment', 'is_active')
    permission_classes = [permissions.IsAuthenticated]


class SamplePreparationView(LoginRequiredMixin, ListView):
    raise_exception = True
    template_name = 'tasex/owner_panel_products.html'
    context_object_name = 'products'

    def get_queryset(self):
        # Sample.objects.filter(sample_set__panel_id=self.kwargs['pk']).select_related('product')
        products = (Panel.objects
                    .filter(id=self.kwargs['pk'])
                    .values_list('experiment__product_A', 'experiment__product_B'))
        return Product.objects.filter(pk__in=list(*products))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['samplesA'] = (
            Sample.objects
            .filter(product_id=context['products'][0])
            .filter(sample_set__panel_id=self.kwargs['pk'])
            .order_by('sample_set__id')
        )
        context['samplesB'] = (
            Sample.objects
            .filter(product_id=context['products'][1])
            .filter(sample_set__panel_id=self.kwargs['pk'])
            .order_by('sample_set__id')
        )

        return context


class SampleSetsView(LoginRequiredMixin, ListView):
    raise_exception = True
    template_name = 'tasex/owner_panel_sets.html'
    context_object_name = 'sample_sets'

    def get_queryset(self):
        return SampleSet.objects.filter(panel_id=self.kwargs['pk']).prefetch_related('samples')


class AdminPanelView(LoginRequiredMixin, DetailView):
    template_name = 'tasex/admin_panel.html'
    model = Panel
    # 404 instead of redirect to login page for not logged-in user
    # raise_exception = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        panel = self.kwargs.get('pk')
        context['statuses'] = Panel.PanelStatus
        if panel:
            results = Result.objects.filter(sample_set__in=SampleSet.objects.filter(panel_id=panel))
            context['results'] = results.count()
            answers = Answer.objects.filter(result__in=results)
            questions = PanelQuestion.objects.filter(panel_id=panel)
            if questions.count():
                context['answers'] = answers.count() // questions.count()
            else:
                context['answers'] = 'No questions asked'
        return context


class ResultsView(DetailView):
    model = Panel
    template_name = 'tasex/panel_results.html'
    context_object_name = 'panel'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        if not Result.objects.filter(sample_set__panel=self.object).exists():
            self.template_name = 'tasex/panel_results_empty.html'
            return context
        # Add in a QuerySet of all the books
        context["panel_result"] = PanelResult(self.object)
        context["survey_plots"] = SurveyPlots(self.object)
        return context


class PanelState:
    def __init__(self, panel_id, step=1, sample_set=None, result=None):
        self.panel_id = panel_id
        self.step = step
        self.sample_set = sample_set
        self.result = result


class PanelStep1(FormView):
    # form_class = SingleSampleForm
    template_name = 'tasex/panel_step_1.html'

    def __init__(self):
        super().__init__()
        self.panel_id = None
        self.panel_state = None

    def form_valid(self, form):
        if form.is_valid():
            self.panel_state.step += 1

            sample_set_id = form.cleaned_data.get('sample_set_id')
            if sample_set_id:
                self.panel_state.sample_set = sample_set_id

            are_samples_correct = form.cleaned_data.get('are_samples_correct')
            if are_samples_correct == 'False':
                # reset panel
                self.panel_state = PanelState(self.panel_id)
            if are_samples_correct == 'True':
                sample_set = SampleSet.objects.filter(id=self.panel_state.sample_set).update(is_used=True)

            odd_sample = form.cleaned_data.get('odd_sample')
            if odd_sample:
                self.panel_state.result = Result.objects.create(
                    sample_set=SampleSet.objects.get(id=self.panel_state.sample_set),
                    odd_sample=Sample.objects.get(id=odd_sample)
                )
                self.panel_state.result = self.panel_state.result.id

            self.request.session.get('panels')[self.panel_id] = self.panel_state.__dict__
            self.request.session.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('tasex:panel', kwargs={'pk': self.kwargs.get('pk')})

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        form_kwargs['panel_state'] = self.panel_state
        return form_kwargs

    def get_form_class(self):
        return FORM_CLASSES.get(self.panel_state.step)

    def get_context_data(self, **kwargs):
        form_titles = {
            1: "Sprawdzamy, czy masz właściwy zestaw próbek",
            2: "Sprawdzamy, czy masz właściwy zestaw próbek",
            3: "Dwie próbki są identyczne. Jedna próbka jest inna - która?",
        }
        context = super().get_context_data(**kwargs)
        context['title'] = form_titles.get(self.panel_state.step)
        print(self.panel_state)
        return context

    def setup(self, request, *args, **kwargs):
        self.panel_id = kwargs.get('pk')
        self.panel_state = PanelState(**request.session.get('panels').get(self.panel_id))
        return super().setup(request, *args, **kwargs)


class PanelQuestionsView(FormView):
    form_class = PanelQuestionsForm
    template_name = 'tasex/panel_questions.html'

    def __init__(self):
        super().__init__()
        self.panel_id = None
        self.panel_state = None

    def setup(self, request, *args, **kwargs):
        self.panel_id = kwargs.get('pk')
        self.panel_state = PanelState(**request.session.get('panels').get(self.panel_id))
        return super().setup(request, *args, **kwargs)

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        # form_kwargs['panel_state'] = self.panel_state
        form_kwargs['questions'] = PanelQuestion.objects.filter(panel_id=self.panel_id)
        return form_kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_a = Panel.objects.get(id=self.panel_id).experiment.product_A
        result = Result.objects.get(id=self.panel_state.result)
        odd = result.odd_sample
        other = list(result.sample_set.samples.values_list('code', flat=True))
        other.remove(odd.code)
        if odd.product == product_a:
            context['product_a'] = [odd.code]
            context['product_b'] = other
        else:
            context['product_b'] = [odd.code]
            context['product_a'] = other

        return context

    def form_valid(self, form):
        # increment panel_state.step
        self.panel_state.step += 1
        self.request.session.get('panels')[self.panel_id] = self.panel_state.__dict__
        self.request.session.save()

        # save answers
        result = Result.objects.get(id=self.panel_state.result)
        if Answer.objects.filter(result=result).exists():
            raise ValidationError('Answers already recorded')
        for question in PanelQuestion.objects.filter(panel_id=self.panel_id):
            answer = form.cleaned_data.get(str(question.id))
            if answer:
                answer_text = question.scale.points.get(code=answer).text
                Answer.objects.create(
                    question=question,
                    result=result,
                    answer_code=answer,
                    answer_text=answer_text
                )
        return HttpResponseRedirect(
            reverse('tasex:panel', kwargs={'pk': self.kwargs.get('pk')})
        )


class WaitForFinishView(DetailView):
    model = Panel
    template_name = 'tasex/panel_wait_for_finish.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        panel = self.get_object()
        result_id = self.request.session.get('panels').get(str(panel.id)).get('result')
        result = Result.objects.get(id=result_id)
        is_correct = result.is_correct
        context["is_correct"] = is_correct
        odd_product = (
            Sample.objects
            .filter(sample_set=result.sample_set)
            .values('product_id')
            .annotate(cnt=models.Count('product_id'))
            .filter(cnt=1)
            .values_list('product_id', flat=True)[0]
        )
        odd_sample = (

backend/tasex/templates/tasex/footer.html
</body>
</html>

backend/tasex/templates/tasex/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasting experiments</title>
    <!-- {% block title %}{% endblock %} -->
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>

backend/tasex/templates/tasex/owner_panel_products.html
<html><head>
{% load static %}
<link rel="stylesheet" href="{% static 'tasex/owner.css' %}">

</head><body>

<table class="simple">
<thead>
    <tr><th>Lp</th><th>{{ products.0.brew_id }}</th></tr>
</thead>
<tbody>
{% for sample in samplesA %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ sample.code }}</td>
    </tr>
{% endfor %}
</tbody>
</table>
<div class="pagebreak"> </div>
<table class="simple">
<thead>
    <tr><th>Lp</th><th>{{ products.1.brew_id }}</th></tr>
</thead>
<tbody>
{% for sample in samplesB %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ sample.code }}</td>
    </tr>
{% endfor %}
</tbody>
</table>
</body></html>

backend/tasex/templates/tasex/owner_panel_sets.html
{#<html><head>#}
{##}
{#{% load static %}#}
{#<link rel="stylesheet" href="{% static 'tasex/owner.css' %}">#}
{##}
{#</head><body>#}
{%  include 'tasex/header.html' %}
{#<table class="simple">#}
<div class="container">
<table class="table table-striped">
<thead>
    <tr><th>Lp</th><th>Próbka 1</th><th>Próbka 2</th><th>Próbka 3</th></tr>
</thead>
<tbody>
{% for sample_set in sample_sets %}
    <tr>
        <td>{{ forloop.counter }}</td>
        {%  for sample in sample_set.samples.all|dictsort:'code' %}
            <td>{{ sample.code }}</td>
        {% endfor %}
    </tr>
{% endfor %}
</tbody>
</table>
</div>
{% include 'tasex/footer.html' %}
{#</body></html>#}

backend/tasex/templates/tasex/panel_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Triangle Testing Demo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}

</head>
<body class="bg-light-subtle">

    {% include 'demo/messages.html' %}

    <div class="container p-5 text-bg-primary text-center rounded-top shadow">
        <h1>
            {% block title %}

            {% endblock %}
        </h1>
    </div>




    <div  class="container bg-light h-100 p-3 shadow">

        {% block content %}

        {% endblock %}
    </div>

</body>
</html>

backend/tasex/templates/tasex/panel_closed.html
{% extends 'tasex/panel_base.html' %}
{% block title %}
Panel <b>{{ panel.experiment.title }}</b> is closed.
{% endblock title %}

backend/tasex/templates/tasex/panel_planned.html
{% extends 'tasex/panel_base.html' %}
{% block title %}
Panel will begin shortly.
{% endblock title %}

backend/tasex/templates/tasex/panel_questions.html
{% extends 'tasex/panel_base.html' %}
{% block title %}
Pytania dodatkowe
{% endblock title %}
{% block content %}
    <h3>Produkty, które oceniałeś:</h3>
    <table border="1" class="table">
        <tr><th>Produkt</th><th>A</th><th>B</th></tr>
        <tr><th>Próbki</th>
            <td>
                {% for product in product_a %}
                    {{ product }} <br/>
                {% endfor%}
            </td>
            <td>
                {% for product in product_b %}
                    {{ product }} <br/>
                {% endfor%}
            </td></tr>
    </table>
    <h3>Odpowiedz na poniższe pytania:</h3>

    <form  method="post">
        {% csrf_token %}

            {{ form.as_p }}

        <div>
            <input type="submit" value="Submit" class="btn btn-primary">
        </div>

    </form>
{% endblock content %}

backend/tasex/templates/tasex/panel_results.html
{% extends 'tasex/panel_base.html' %}
{% block title %}
Panel <b>{{ panel.experiment.title }}</b> results<br/>
{% endblock title %}
{% block content %}
Correct answers:
{{ panel_result.correct }} / {{ panel_result.participants }}
({{ panel_result.percent_correct }}%)
<br/>
P-value: {{ panel_result.p_value }} <br/>
<img src="data:image/png;base64,{{ panel_result.plot_correct }}" alt="Plot with result data"  class="img-fluid">

{% for plot in survey_plots.plots %}
    <img src="data:image/png;base64,{{ plot }}" alt="Another plot" class="img-fluid">
{% endfor %}
{% endblock content %}

backend/tasex/templates/tasex/panel_results_empty.html
{% extends 'tasex/panel_base.html' %}
{% block title %}
This panel results cannot be presented as noone answered the survey!
{% endblock title %}

backend/tasex/templates/tasex/panel_step_1.html
{% extends 'tasex/panel_base.html' %}
{% load static %}
{% block title %}
{{ title }}
{% endblock title %}
{% block content %}
<form  method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{% endblock content %}

backend/tasex/templates/tasex/panel_wait_for_finish.html
{% extends 'tasex/panel_base.html' %}
{% block title %}
Panel <b>{{ panel.description }}</b> is still accepting responses.
Please wait until panel closes to see the results.
{% endblock title %}

{% block content %}
    {% if is_correct %}
        <div class="alert alert-success">
            You have <strong>correctly</strong> identified the odd sample.
        </div>
    {% else %}
        <div class="alert alert-danger">
            You have selected <strong>wrong</strong> sample.
        </div>
        Correct sample number: {{ correct_sample }}</br>
    {% endif %}
    You have selected sample number: {{ user_sample }}

    {% if products %}
        <h5 class="display-6">Experiment description:</h5>
        {{ panel.experiment.description }}
        <h5 class="display-6">Samples you've judged:</h5>
        <table class="table table-hover">
            <tr>
                <th>Product</th><th>Sample code</th>
            </tr>
            {% for item in products %}
                <tr>
                    <td>{{ item.product__description }}</td>
                    <td>{{ item.code }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock content %}

backend/tasex/templates/tasex/swagger-ui.html
<!DOCTYPE html>
<html>
  <head>
    <title>Swagger</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script>
    const ui = SwaggerUIBundle({
        url: "{% url schema_url %}",
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout",
        requestInterceptor: (request) => {
          request.headers['X-CSRFToken'] = "{{ csrf_token }}"
          return request;
        }
      })
    </script>
  </body>
</html>

backend/tasex/templates/tasex/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasting Experiments</title>
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
</head>
<body>
<h1 align="center" class="display-1">Tasting Experiments</h1>
{% load static %}
<center>
    <img src="{% static 'tasex/logo.png' %}" align="center">
</center><br/>
<div align="center">
    <a href="#" class="btn btn-outline-primary disabled">Login</a>
    <a href="{% url 'demo:index' %}" class="btn btn-outline-primary">Demo</a>
</div>


</body>
</html>